# Generated by Django 6.0.5 on 2026-10-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Routes',
            new_name='Route',
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['departure_time']},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('route', 'seat_number')},
        ),
    ]
